apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dwk-1-11-claim
spec:
  storageClassName: dwk-local-1-11
  volumeName: dwk-1-11-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
