apiVersion: v1
kind: Service
metadata:
  name: pingpong-1-9-svc
spec:
  type: ClusterIP
  selector:
    app: pingpong-1-9
  ports:
    - name: http
      protocol: TCP
      port: 2346
      targetPort: 3000
