apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: log-output-shared-data-pvc
  labels:
    app: log-output
    exercise: "1.13"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
