apiVersion: v1
kind: Service
metadata:
  name: the-project-1-8-svc
spec:
  type: ClusterIP
  selector:
    app: the-project-1-8
  ports:
    - name: http
      protocol: TCP
      port: 2345
      targetPort: 3000
